# Generated by Django 4.0.6 on 2022-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TropikoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255, verbose_name='Name')),
                ('P_NUM', models.IntegerField(verbose_name='Phone')),
                ('EMAIL', models.EmailField(max_length=254, verbose_name='Email')),
                ('MESSAGE', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
